# Generated by Django 3.0.5 on 2020-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=32)),
                ('calorie', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('description', models.TextField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('limit', models.BooleanField(default=False)),
            ],
        ),
    ]
